# Generated by Django 4.1.2 on 2022-12-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='usuario',
        ),
    ]
