# Generated by Django 4.1.2 on 2022-12-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_productos_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
    ]
